### ISSUE TITLE
ImportError: cannot import name LogentriesHandler

### ISSUE THREAD

**Issue by jklemm** [logentries/le_python#18]
Hi,

I'm using Mac OS X 10.9.4 and Python 2.7.5

I have created my account on Logentries, and using the code generated by the app (with token), running the logging.py on the Terminal.  

**The installation:**

$ sudo pip install logentries
Downloading/unpacking logentries
  Downloading Logentries-0.2.1.tar.gz
  Running setup.py egg_info for package logentries
    
Installing collected packages: logentries
  Running setup.py install for logentries
    
Successfully installed logentries
Cleaning up...
$ sudo pip freeze | grep entries
LogentriesLogger==0.2.1

**The snippet that I use:**

#!/usr/bin/env python
from logentries import LogentriesHandler
import logging
import time
log = logging.getLogger('logentries')
log.setLevel(logging.INFO)
test = LogentriesHandler('--- MY TOKEN ---')
log.addHandler(test)
log.warn("Warning message")
log.info("Info message")
time.sleep(10)

**When run the snippet show this stack trace:**

$ python logging.py
Traceback (most recent call last):
  File "logging.py", line 3, in <module>
    from logentries import LogentriesHandler
  File "/Library/Python/2.7/site-packages/logentries/__init__.py", line 1, in <module>
    from .utils import LogentriesHandler
  File "/Library/Python/2.7/site-packages/logentries/utils.py", line 9, in <module>
    import logging
  File "/Users/myuser/Desktop/logging.py", line 3, in <module>
    from logentries import LogentriesHandler

**Comment by StephenHynes7** [comment]
Can you try the latest version? https://pypi.python.org/pypi/Logentries

**Comment by jklemm** [comment]
Thanks, it works!
