### ISSUE TITLE
Remove broken PyPI package

### ISSUE THREAD

**Issue by graingert** [logentries/le_python#20]
https://pypi.python.org/pypi/Logentries/0.2 is broken

It hosts a LogentriesLogger==0.2.1 package instead of the expected logentries package

Which is available at the apparantly canonical https://pypi.python.org/pypi/LogentriesLogger/ location.

**Comment by StephenHynes7** [comment]
Should be fixed now.

**Comment by graingert** [comment]
can you create another package at LogentriesLogger that depends on Logentries?

Maybe with the readme with a big "moved!" url?

**Comment by StephenHynes7** [comment]
Yeah sounds like a good idea. Iv created an issue on github and mentioned
you about the issue
