### ISSUE TITLE
Unable to connect: incorrect port documentation

### ISSUE THREAD

**Issue by reiven** [logentries/le_python#26]
Hi, i'm trying to use python logentries behind a firewall, but reading https://github.com/logentries/le_python/blob/master/logentries/utils.py i see it tries to use port 10000 and documentation says it should use ports 80 and 443.
It will be a good idea to add this information somewhere in the README

**Comment by StephenHynes7** [comment]
Hey iv updated the appender to use ports 80 and 443 now they used to use port 1000. I have updated the documentation to make this clear aswell.
