### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by travisbrady** [logentries/le_python#31]
Also, the 0.5 package on pypi has broken our build, please fix ASAP.

On a fresh clone I get:
```python
In [1]: import logentries
  File "logentries/utils.py", line 187
    finally:
          ^
SyntaxError: invalid syntax
```

**Comment by StephenHynes7** [comment]
These issues should be fixed now, apologies for the error.

**Comment by graingert** [comment]
sorry about that, cleaned up in #34
