### ISSUE TITLE
queue full exception not handled

### ISSUE THREAD

**Issue by jtheuer** [logentries/le_python#48]
If the queue is full, the Full exception https://docs.python.org/2/library/queue.html#Queue.Full isn't handled but propagated to the caller.
https://github.com/logentries/le_python/blob/master/logentries/utils.py#L192

The logger should drop the message instead. Better than crashing the the program.

Jan

**Comment by jcftang-r7** [comment]
From a previous discussion as far as I recall the queue full behaviour is meant to block the thread.

**Comment by jtheuer** [comment]
Would mean that your customers' programs block when there are network issues or the logentries api is down. I as a customer certainly wouldn't want that. You java log appender drops the messages when the queue is full, btw.

**Comment by vilda** [comment]
Agree with @jtheuer the emit method should not affect the logging thread. Creating #51 for rescue...

**Comment by vilda** [comment]
Thanks for reporting, fixed now!
