### ISSUE TITLE
v0.16 on pypi broken for Windows

### ISSUE THREAD

**Issue by Syeberman** [logentries/le_python#59]
``pip install logentries`` breaks on Windows. v0.15 installed fine for me, but installing v0.16 results in:

(.venv) C:\Work\external\le_python>python setup.py install
running install
running bdist_egg
error: error in 'egg_base' option: '/tmp' does not exist or is not a directory

**Comment by eflanagan-r7** [comment]
@Syeberman Hi. I've released 0.17, which includes @nicholjy 's fix. Let me know if there's any problems still

**Comment by Syeberman** [comment]
Thanks, it works!
